In [4]:
import numpy as np

arr = np.array([5, 8, 3, 10])
print(arr)
print(type(arr))

[ 5  8  3 10]
<class 'numpy.ndarray'>


In [10]:
import numpy as np

arr_1 = np.array([5, 8, 3, 10])
arr_2 = np.array([6, 2, 8, 11])

result_addition = arr_1 + arr_2
print(result_addition)


[11 10 11 21]


In [ ]:
result_subtraction = arr_1 - arr_2
print(result_subtraction)

[-1  6 -5 -1]


In [8]:
result_multiple = arr_1 * arr_2
print(result_multiple)

[ 30  16  24 110]


In [11]:
result_devision = arr_1 / arr_2
print(result_devision)

[0.83333333 4.         0.375      0.90909091]


In [12]:
arr_1 = np.array([16, 9, 36, 100])
print(np.sqrt(arr_1))

[ 4.  3.  6. 10.]


In [13]:
print(np.sum(arr_1))

161


In [17]:
print(np.max(arr_1))


100


In [16]:
print(np.min(arr_1))

9


In [ ]:
arr_1 = np.array([[9, 10, 5] , [8, 12, 20] ])
print(arr_1)  
print(arr_1.size)
print(arr_1.shape)
print(arr_1.ndim)

[[ 9 10  5]
 [ 8 12 20]]
6
(2, 3)
2


In [ ]:
arr_1 = np.array([[[9, 10, 5], [8, 12, 20]], [[1, 2, 3], [4, 5, 6]]])
print(arr_1.size)
print(arr_1.shape)
print(arr_1.ndim)

12
3
(2, 2, 3)


In [33]:
array = np.array([1, 2, True ])
print(array.dtype)

int64


In [36]:
arr_2 = np.array([[5, 3, 8], [4, 9, 10]])
print(arr_2[1, 2]) 
print(arr_2[-2, -2])

10
3


In [37]:
arr = np.array([30, 10, 40, 50, 20])
condition = arr > 25
print(condition)

[ True False  True  True False]


In [38]:
print(arr[condition]) 

[30 40 50]


In [39]:
print(arr[arr > 25])  

[30 40 50]


In [ ]:
arr = np.array([30, 10, 40, 50, 20])
print(arr[(arr > 25) & (arr < 45)])

[30 40]


In [54]:
body_tempreture = np.array([
    [31, 30, 28], 
    [29, 29, 32],
    [26, 24, 27], 
    [31, 34, 35], 
    [28, 31, 30]
    ])

daily_average = np.mean(body_tempreture)
# daily_average = np.sum(body_tempreture)/(body_tempreture.size)
print(daily_average)

print(body_tempreture[body_tempreture > daily_average])


29.666666666666668
[31 30 32 31 34 35 31 30]


In [ ]:
print(np.zeros((2, 3))) 
print(np.zeros(5))


[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [60]:
print(np.ones((2, 3)))                  
print(np.ones(5))

[[1. 1. 1.]
 [1. 1. 1.]]
[1. 1. 1. 1. 1.]


In [62]:
print(np.full((2, 3), 7))
print(np.full(5, 7))

[[7 7 7]
 [7 7 7]]
[7 7 7 7 7]


In [68]:
print(np.full((2, 3), (1,2,3)))

[[1 2 3]
 [1 2 3]]


In [69]:
print(np.empty((2, 3)))

[[4.9e-324 9.9e-324 1.5e-323]
 [4.9e-324 9.9e-324 1.5e-323]]


In [23]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],}

df = pd.DataFrame(data)
print(df)


      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35
3    David   40


In [5]:
print(df.loc[0,'Name'])
print(df.iloc[2, 1])  # Accessing by index

Alice
35


In [88]:
print(df.loc[2])  
print(df.iloc[2]) 

Name    Charlie
Age          35
Name: 2, dtype: object
Name    Charlie
Age          35
Name: 2, dtype: object


In [25]:
df = pd.DataFrame(data, index=['student_1', 'student_2', 'student_3', 'student_4'])
print(df)


              Name  Age
student_1    Alice   25
student_2      Bob   30
student_3  Charlie   35
student_4    David   40


In [7]:
print(df.loc['student_3'])
print(df.iloc[1]) 

Name    Charlie
Age          35
Name: student_3, dtype: object
Name    Bob
Age      30
Name: student_2, dtype: object


In [101]:
print(df.loc[['student_1', 'student_3']])

              Name  Age
student_1    Alice   25
student_3  Charlie   35


In [108]:
age_column = df[['Age']]
print(age_column)

           Age
student_1   25
student_2   30
student_3   35
student_4   40


In [113]:
print(df.columns)  # Displaying column names
print(list(df.columns))  

Index(['Name', 'Age'], dtype='object')
['Name', 'Age']


In [ ]:
print(df.index)  # Displaying index names
print(list(df.index)) 

Index(['student_1', 'student_2', 'student_3', 'student_4'], dtype='object')
['student_1', 'student_2', 'student_3', 'student_4']


In [8]:
print(df.size)
print(df.shape)
print(len(df))  # Number of rows

8
(4, 2)
4


In [ ]:
# Converting DataFrame to NumPy array
print(df.values) 
print(type(df.values))

[['Alice' 25]
 ['Bob' 30]
 ['Charlie' 35]
 ['David' 40]]
<class 'numpy.ndarray'>


In [12]:
print(df['Age'].mean()) 
print(df['Age'].sum()) 

32.5
130


In [36]:
# How to add a new column to the DataFrame
df['City'] = ['New York', 'Los Angeles', 'Chicago', 'Houston']
df['Salary'] = [50000, 60000, 70000, 80000]
print(df)

              Name  Age         City  Salary
student_1    Alice   25     New York   50000
student_2      Bob   30  Los Angeles   60000
student_3  Charlie   35      Chicago   70000
student_4    David   40      Houston   80000


In [37]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)
print(type(filtered_df))

              Name  Age     City  Salary
student_3  Charlie   35  Chicago   70000
student_4    David   40  Houston   80000
<class 'pandas.core.frame.DataFrame'>


In [38]:
filtered_df = df[(df['Age'] > 28) & (df['Salary'] < 65000)]
print(filtered_df)

          Name  Age         City  Salary
student_2  Bob   30  Los Angeles   60000


In [ ]:
#  1 Question:
data = {"StudentID":[1001, 1002, 1003, 1004, 1005],
        "Name":["Ayesha","Nimal","Tharindu","Kasun","Shashini"],
        "Assginment1":[78, 65, 88, 50, 80],
        "Assginment2":[85, 70, 90, 45, 75],
        "FinalExam":[90, 72, 95, 60, 85]
        }

df = pd.DataFrame(data)
print(df)


   StudentID      Name  Assginment1  Assginment2  FinalExam
0       1001    Ayesha           78           85         90
1       1002     Nimal           65           70         72
2       1003  Tharindu           88           90         95
3       1004     Kasun           50           45         60
4       1005  Shashini           80           75         85


In [ ]:
# 2 Question:
print(df[df["FinalExam"] > 80] [["Name","FinalExam"]]) 

       Name  FinalExam
0    Ayesha         90
2  Tharindu         95
4  Shashini         85


In [72]:
#  3 Question:
df["Average"] = (df['Assginment1'] + df['Assginment2'] + df['FinalExam']) / 3
print(df)

   StudentID      Name  Assginment1  Assginment2  FinalExam    Average
0       1001    Ayesha           78           85         90  84.333333
1       1002     Nimal           65           70         72  69.000000
2       1003  Tharindu           88           90         95  91.000000
3       1004     Kasun           50           45         60  51.666667
4       1005  Shashini           80           75         85  80.000000


In [78]:
#  4 Question:
highest_average_student = df[df["Average"] == df["Average"].max()]
print(highest_average_student[["Name", "Average"]])

       Name  Average
2  Tharindu     91.0


In [ ]:
#  5 Question:
total_assignments = df["Assginment1"].sum()
print("Total Marks for all students:",total_assignments)

Total Marks for all students: 361


In [80]:
df = pd.read_csv('test.csv')
print(df)
print(type(df))

      John Doe  30     New York
0   Jane Smith  25  Los Angeles
1  Bob Johnson  40      Chicago
<class 'pandas.core.frame.DataFrame'>
